source:
  type: mysql
  hostname: mysql
  port: 3306
  username: smartcache
  password: smartcache
  tables: smartcache.\.*
  server-id: 5400-5404
  server-time-zone: UTC

sink:
  type: nats
  name: NATS JetStream Producer
  url: nats://nats:4222
  subject: mysql-cdc-changes.{tableName}
  stream: cdc-stream
  create-stream: true
  ack-policy: explicit
  max-pending: 1000
  headers:
    - tableName: "{tableName}"
    - operationType: "{operationType}"
    - timestamp: "{timestamp}"
  deliver-policy: all
  ack-wait: 30s

pipeline:
  name: MySQL to NATS Producer Pipeline
  parallelism: 1
  checkpoint.interval: 1000