include:
  - ./docker-compose-cdc-sync.yml
  - ./docker-compose-ojp.yml

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - a8

  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=fluxDB
      - GF_SECURITY_ADMIN_USER=fluxDB
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      #- GF_INSTALL_PLUGINS=grafana-piechart-panel,marcusolsson-json-datasource,marcusolsson-dynamictext-panel
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/a8-turbo-dashboard.json
      - GF_SERVER_ROOT_URL=http://localhost:3000/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    networks:
      - a8
    depends_on:
      - prometheus
    volumes:
      - ./docker/grafana/config/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./docker/grafana/config/datasources:/etc/grafana/provisioning/datasources
      - ./docker/grafana/config/dashboards:/var/lib/grafana/dashboards
      - ./docker/grafana/data:/var/lib/grafana

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    container_name: phpredisadmin
    hostname: phpredisadmin
    ports:
      - "50082:80"
    networks:
      - a8
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_NAME=redis
    depends_on:
      - redis

networks:
  a8:
    external: false