services:
  # 1. 自定义 DNS 服务器（dnsmasq）
  # dns-server:
  #   image: andyshinn/dnsmasq
  #   container_name: dns-server
  #   volumes:
  #     - ./docker/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
  #   ports:
  #     - "50053:53/udp"
  #     - "50053:53/tcp"
  #   networks:
  #     a8:
  #       ipv4_address: 172.24.0.2
  #   cap_add:
  #     - NET_ADMIN

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/prometheus/data:/prometheus
    networks:
      a8:
        ipv4_address: 172.24.0.3

  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=fluxDB
      - GF_SECURITY_ADMIN_USER=fluxDB
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/a8-turbo-dashboard.json
      - GF_SERVER_ROOT_URL=http://localhost:3000/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    networks:
      a8:
        ipv4_address: 172.24.0.4
    depends_on:
      - prometheus
    volumes:
      - ./docker/grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - ./docker/grafana/config/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./docker/grafana/config/datasources:/etc/grafana/provisioning/datasources
      - ./docker/grafana/config/dashboards:/var/lib/grafana/dashboards

  redis:
    image: redis-server-with-cache-cli
    container_name: redis
    build:
      context: ./docker/redis
      dockerfile: ./Dockerfile
    hostname: redis
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports:
      - 6379:6379
    networks:
      a8:
        ipv4_address: 172.24.0.5
    volumes:
      - ./docker/redis/data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    environment:
      - REDIS_ADDR=redis://redis:6379
    networks:
      a8:
        ipv4_address: 172.24.0.6
    depends_on:
      - redis

  phpredmin:
    image: sasanrose/phpredmin:latest
    container_name: phpredmin
    hostname: phpredmin
    networks:
      a8:
        ipv4_address: 172.24.0.7
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./docker/phpredmin/custom-apache.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/phpredmin/config.php:/var/www/html/phpredmin/config.php
      - ./docker/phpredmin/index.php:/var/www/html/phpredmin/public/index.php
