networks:
  a8:
    external: false


include:
  - ./docker-compose-cdc-sync.yml
  - ./docker-compose-kong.yml
#  - ./docker-compose-ojp.yml
#  - ./docker-compose-shopservice.yml
  - ./docker-compose-ojp-local.yml


services:
  # 1. 自定义 DNS 服务器（dnsmasq）
  dns-server:
    image: andyshinn/dnsmasq
    volumes:
      - ./docker/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf  # 挂载解析规则
    ports:
      - "50053:53/udp"
      - "50053:53/tcp"
    networks:
      - a8
    cap_add:
      - NET_ADMIN

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    # 移除对外暴露的端口，通过Kong网关访问
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - a8

  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    container_name: grafana
    # 移除对外暴露的端口，通过Kong网关访问
    # ports:
    #   - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=fluxDB
      - GF_SECURITY_ADMIN_USER=fluxDB
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      #- GF_INSTALL_PLUGINS=grafana-piechart-panel,marcusolsson-json-datasource,marcusolsson-dynamictext-panel
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/a8-turbo-dashboard.json
      - GF_SERVER_ROOT_URL=http://localhost:3000/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    networks:
      - a8
    depends_on:
      - prometheus
    volumes:
      - ./docker/grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - ./docker/grafana/config/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./docker/grafana/config/datasources:/etc/grafana/provisioning/datasources
      - ./docker/grafana/config/dashboards:/var/lib/grafana/dashboards
      - ./docker/grafana/data:/var/lib/grafana

  redis:
    image: redis-server-with-cache-cli
    build:
      context: ./docker/redis
      dockerfile: ./Dockerfile
    hostname: redis
    container_name: redis-server-with-cache-cli
    # 移除对外暴露的端口，通过Kong网关访问（如需要）
    ports:
      - 6379:6379
    networks:
      - a8

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    # 移除对外暴露的端口，通过Kong网关访问
    # ports:
    #   - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
    networks:
      - a8
    depends_on:
      - redis

  phpredmin:
    image: sasanrose/phpredmin:latest
    container_name: phpredmin
    hostname: phpredmin
    # 移除对外暴露的端口，通过Kong网关访问
    # ports:
    #   - "50082:80"
    networks:
      - a8
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./docker/phpredmin/custom-apache.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/phpredmin/config.php:/var/www/html/phpredmin/config.php
      - ./docker/phpredmin/index.php:/var/www/html/phpredmin/public/index.php

