services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: mysql
    networks:
      - a8
    # 移除对外暴露的端口，通过Kong网关访问（如需要）
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=a8
      #      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=smartcache
      - MYSQL_PASSWORD=smartcache
      - MYSQL_DATABASE=smartcache
      # cd /opt/flink-cdc  ./bin/flink-cdc.sh --jar /opt/flink-cdc/lib/mysql-connector-java.jar --flink-home $FLINK_HOME /opt/flink_jobs/mysql-to-nats-consume-to-starrocks.yaml


  mysql5:
    image: mysql:5.7
    hostname: mysql5
    container_name: mysql5
    networks:
      - a8
    command: --port=3307 --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci --lower_case_table_names=1 --skip-name-resolve
    ports:
      - 3307:3307
    volumes:
      - ./docker/mysql5/conf.d:/etc/mysql/conf.d
      - ./docker/mysql5/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql5/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=a8
      - MYSQL_USER=smartcache
      - MYSQL_PASSWORD=smartcache
      - MYSQL_DATABASE=smartcache

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    command:
      - "--mysqld.username=smartcache:smartcache"
      - "--mysqld.address=mysql:3306"
    environment:
      - DATA_SOURCE_NAME=smartcache:smartcache@tcp(mysql:3306)/smartcache
    # 移除对外暴露的端口，通过Kong网关访问
    # ports:
    #   - "9104:9104"
    networks:
      - a8

    depends_on:
      - mysql

  starrocks:
    image: starrocks/allin1-ubuntu
    container_name: starrocks
    # 移除对外暴露的端口，通过Kong网关访问（如需要）
    ports:
      - "9030:9030"
      # - "8030:8030"
      # - "8040:8040"
      #   - "8080:8080"
    tty: true
    privileged: true
    networks:
      - a8

networks:
  a8:
    external: false
