# IP Range: 172.24.0.20 - 172.24.0.39 (CDC & Data Integration)
services:
  seatunnel-master:
    image: apache/seatunnel
    container_name: seatunnel-master
    environment:
      - ST_DOCKER_MEMBER_LIST=seatunnel-master,seatunnel-worker1
      - HZ_NETWORK_RESTAPI_ENABLED=true
    volumes:
      - ./docker/seatunnel/lib:/ojp-cdc-monitor
      - ./docker/seatunnel/config/seatunnel.yaml:/opt/seatunnel/config/seatunnel.yaml:ro
      - ./docker/seatunnel/config/hazelcast-master.yaml:/opt/seatunnel/config/hazelcast-master.yaml:ro
      - ./docker/seatunnel/data/imap:/opt/seatunnel/data/imap
    entrypoint: /bin/sh -c "rm -f /opt/seatunnel/lib/connector-cdc-base-*.jar && cp -f /ojp-cdc-monitor/* /opt/seatunnel/lib/ && /opt/seatunnel/bin/seatunnel-cluster.sh -r master"
    ports:
      - "5801:5801"
      - "8080:8080"
    networks:
      a8:
        ipv4_address: 172.24.0.20

  seatunnel-worker1:
    image: apache/seatunnel
    container_name: seatunnel-worker1
    environment:
      - ST_DOCKER_MEMBER_LIST=seatunnel-master,seatunnel-worker1
      - HZ_NETWORK_RESTAPI_ENABLED=true
    volumes:
      - ./docker/seatunnel/lib:/ojp-cdc-monitor
      - ./docker/seatunnel/config/seatunnel.yaml:/opt/seatunnel/config/seatunnel.yaml:ro
      - ./docker/seatunnel/config/hazelcast-worker.yaml:/opt/seatunnel/config/hazelcast-worker.yaml:ro
      - ./docker/seatunnel/data/imap:/opt/seatunnel/data/imap
    entrypoint: /bin/sh -c "rm -f /opt/seatunnel/lib/connector-cdc-base-*.jar && cp -f /ojp-cdc-monitor/* /opt/seatunnel/lib/ && /opt/seatunnel/bin/seatunnel-cluster.sh -r worker"
    depends_on:
      - seatunnel-master
    networks:
      a8:
        ipv4_address: 172.24.0.21
