networks:
  a8:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16

include:
  - ./docker-compose-infra.yml
  - ./docker-compose-db.yml
  - ./docker-compose-cdc-sync-zeta.yml
  - ./docker-compose-kong.yml
  - ./docker-compose-skywalking.yml
  - ./docker-compose-sentinel.yml

services:
  # --------------------------------------------------------------------------
  #  业务服务 - 基础定义（无环境特定配置）
  # --------------------------------------------------------------------------

  ojp-server:
    image: fluxdb-server:0.0.8-alpha
    build:
      context: .
      dockerfile: ojp/ojp-server/Dockerfile
    container_name: ojp-server
    hostname: ojp-server
    networks:
      a8:
        ipv4_address: 172.24.0.40
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms512m -Xmx1024m
      - SW_AGENT_NAME=ojp-server
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=skywalking-oap:11800
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8010/api/actuator/health" ]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3
    restart: on-failure
    volumes:
      - ./docker/ojp/server/logs:/app/logs
      - ./docker/ojp/server/application.yml:/app/config/application.yml
      - ./docker/ojp/license:/etc/ojp/license
    depends_on:
      - redis
      - ojp-sql-translator

  shopservice:
    image: fluxdb-shopservice:0.0.7-alpha
    build:
      context: ./ojp/shopservice
      dockerfile: Dockerfile
    container_name: shopservice
    hostname: shopservice
    networks:
      a8:
        ipv4_address: 172.24.0.42
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms256m -Xmx512m
    volumes:
      - ./docker/ojp/shopservice/logs:/app/logs
      - ./docker/ojp/shopservice/application.properties:/app/config/application.properties
    depends_on:
      - redis
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8280/actuator/health" ]
      interval: 300s
      timeout: 10s
      start_period: 600s
      retries: 3
    restart: on-failure

  ojp-sql-translator:
    build:
      context: ./ojp/ojp-sql-translator
      dockerfile: Dockerfile
    image: ojp-sql-translator:latest
    container_name: ojp-sql-translator
    environment:
      - TZ=Asia/Shanghai
    networks:
      a8:
        ipv4_address: 172.24.0.100

  ojp-ui:
    build:
      context: ./ojp/ojp-ui
      dockerfile: Dockerfile
    image: ojp-ui:latest
    container_name: ojp-ui
    networks:
      a8:
        ipv4_address: 172.24.0.41
    volumes:
      - ./docker/ojp/ui/vite.config.js:/app/vite.config.js
    depends_on:
      - ojp-server
      - shopservice
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/" ]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3