# IP Range: 172.24.0.100 - 172.24.0.119 (Sidecars & Utilities)
services:
  a8-sql-translator:
    build:
      context: ./ojp/ojp-sql-translator
      dockerfile: Dockerfile
    image: ojp-sql-translator:latest
    container_name: a8-sql-translator
    restart: always
    environment:
      - TZ=Asia/Shanghai
    networks:
      a8:
        ipv4_address: 172.24.0.100
