spring.datasource.url=jdbc:ojp[host.docker.internal:8010]_mysql://host.docker.internal:3306/shopdb
spring.datasource.username=root
spring.datasource.password=a8
spring.datasource.driver-class-name=org.openjdbcproxy.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.datasource.type=org.springframework.jdbc.datasource.SimpleDriverDataSource
server.port=8380