package org.openjdbcproxy.grpc.server.service.interceptor.impl;

import com.openjdbcproxy.grpc.OpResult;
import com.openjdbcproxy.grpc.SessionInfo;
import com.openjdbcproxy.grpc.StatementRequest;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.openjdbcproxy.grpc.server.SessionContext;
import org.openjdbcproxy.grpc.server.service.interceptor.StatementServiceGrpcInterceptor;
import org.openjdbcproxy.grpc.server.service.interceptor.StatementServiceInterceptor;
import org.openjdbcproxy.grpc.server.service.interceptor.context.CurrentRequestContext;
import org.openjdbcproxy.grpc.server.utils.StatementRequestValidator;
import org.springframework.stereotype.Component;

import java.sql.Connection;
import java.sql.SQLException;

/**
 * 熔断器拦截器，实现与业务代码中相同的熔断器逻辑
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class SessionInterceptor implements StatementServiceInterceptor {

    /**
     * Finds a suitable connection for the current sessionInfo.
     * If there is a connection already in the sessionInfo reuse it, if not get a fresh one from the data source.
     *
     * @param sessionInfo        - current sessionInfo object.
     * @param startSessionIfNone - if true will start a new sessionInfo if none exists.
     * @return ConnectionSessionDTO
     * @throws SQLException if connection not found or closed (by timeout or other reason)
     */
    public void ensureSession(SessionInfo sessionInfo, boolean startSessionIfNone) throws SQLException {
        CurrentRequestContext current = StatementServiceGrpcInterceptor.getCurrent();
        if (StringUtils.isEmpty(sessionInfo.getSessionUUID())) {
            Connection conn = current.getDataSourceInterceptor().createConnection(sessionInfo);

            if (startSessionIfNone) {
                sessionInfo = current.getSessionManager().createSession(sessionInfo.getClientUUID(), conn);
            }
        }
        current.setCurrentSessionInfo(sessionInfo);
    }

    @Override
    public void preProcessExecuteUpdate(CurrentRequestContext<StatementRequest, OpResult> context) {
        StatementRequest statementRequest = context.getStatementRequest();
        this.ensureSession(statementRequest.getSession(),
                StatementRequestValidator.isAddBatchOperation(statementRequest) || StatementRequestValidator.hasAutoGeneratedKeysFlag(statementRequest));
    }
}
