package org.openjdbcproxy.cache.emulator;

import lombok.RequiredArgsConstructor;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

/**
 * Wraps a Connection to return Oracle-compatible statements.
 * This effectively intercepts ResultSet creation to apply Oracle metadata emulation.
 */
@RequiredArgsConstructor
public class OracleCompatibleConnection implements Connection {

    private final Connection original;

    @Override
    public Statement createStatement() throws SQLException {
        return new OracleCompatibleStatement(original.createStatement(), this);
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return new OracleCompatiblePreparedStatement(original.prepareStatement(sql), this);
    }
    
    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return new OracleCompatibleStatement(original.createStatement(resultSetType, resultSetConcurrency), this);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return new OracleCompatiblePreparedStatement(original.prepareStatement(sql, resultSetType, resultSetConcurrency), this);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return new OracleCompatibleStatement(original.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability), this);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return new OracleCompatiblePreparedStatement(original.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability), this);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return new OracleCompatiblePreparedStatement(original.prepareStatement(sql, autoGeneratedKeys), this);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return new OracleCompatiblePreparedStatement(original.prepareStatement(sql, columnIndexes), this);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return new OracleCompatiblePreparedStatement(original.prepareStatement(sql, columnNames), this);
    }

    // --- Delegation ---

    @Override public CallableStatement prepareCall(String sql) throws SQLException { return original.prepareCall(sql); }
    @Override public String nativeSQL(String sql) throws SQLException { return original.nativeSQL(sql); }
    @Override public void setAutoCommit(boolean autoCommit) throws SQLException { original.setAutoCommit(autoCommit); }
    @Override public boolean getAutoCommit() throws SQLException { return original.getAutoCommit(); }
    @Override public void commit() throws SQLException { original.commit(); }
    @Override public void rollback() throws SQLException { original.rollback(); }
    @Override public void close() throws SQLException { original.close(); }
    @Override public boolean isClosed() throws SQLException { return original.isClosed(); }
    @Override public DatabaseMetaData getMetaData() throws SQLException { return original.getMetaData(); }
    @Override public void setReadOnly(boolean readOnly) throws SQLException { original.setReadOnly(readOnly); }
    @Override public boolean isReadOnly() throws SQLException { return original.isReadOnly(); }
    @Override public void setCatalog(String catalog) throws SQLException { original.setCatalog(catalog); }
    @Override public String getCatalog() throws SQLException { return original.getCatalog(); }
    @Override public void setTransactionIsolation(int level) throws SQLException { original.setTransactionIsolation(level); }
    @Override public int getTransactionIsolation() throws SQLException { return original.getTransactionIsolation(); }
    @Override public SQLWarning getWarnings() throws SQLException { return original.getWarnings(); }
    @Override public void clearWarnings() throws SQLException { original.clearWarnings(); }
    @Override public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException { return original.prepareCall(sql, resultSetType, resultSetConcurrency); }
    @Override public Map<String, Class<?>> getTypeMap() throws SQLException { return original.getTypeMap(); }
    @Override public void setTypeMap(Map<String, Class<?>> map) throws SQLException { original.setTypeMap(map); }
    @Override public void setHoldability(int holdability) throws SQLException { original.setHoldability(holdability); }
    @Override public int getHoldability() throws SQLException { return original.getHoldability(); }
    @Override public Savepoint setSavepoint() throws SQLException { return original.setSavepoint(); }
    @Override public Savepoint setSavepoint(String name) throws SQLException { return original.setSavepoint(name); }
    @Override public void rollback(Savepoint savepoint) throws SQLException { original.rollback(savepoint); }
    @Override public void releaseSavepoint(Savepoint savepoint) throws SQLException { original.releaseSavepoint(savepoint); }
    @Override public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException { return original.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability); }
    @Override public Clob createClob() throws SQLException { return original.createClob(); }
    @Override public Blob createBlob() throws SQLException { return original.createBlob(); }
    @Override public NClob createNClob() throws SQLException { return original.createNClob(); }
    @Override public SQLXML createSQLXML() throws SQLException { return original.createSQLXML(); }
    @Override public boolean isValid(int timeout) throws SQLException { return original.isValid(timeout); }
    @Override public void setClientInfo(String name, String value) throws SQLClientInfoException { original.setClientInfo(name, value); }
    @Override public void setClientInfo(Properties properties) throws SQLClientInfoException { original.setClientInfo(properties); }
    @Override public String getClientInfo(String name) throws SQLException { return original.getClientInfo(name); }
    @Override public Properties getClientInfo() throws SQLException { return original.getClientInfo(); }
    @Override public Array createArrayOf(String typeName, Object[] elements) throws SQLException { return original.createArrayOf(typeName, elements); }
    @Override public Struct createStruct(String typeName, Object[] attributes) throws SQLException { return original.createStruct(typeName, attributes); }
    @Override public void setSchema(String schema) throws SQLException { original.setSchema(schema); }
    @Override public String getSchema() throws SQLException { return original.getSchema(); }
    @Override public void abort(Executor executor) throws SQLException { original.abort(executor); }
    @Override public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException { original.setNetworkTimeout(executor, milliseconds); }
    @Override public int getNetworkTimeout() throws SQLException { return original.getNetworkTimeout(); }
    @Override public <T> T unwrap(Class<T> iface) throws SQLException { return original.unwrap(iface); }
    @Override public boolean isWrapperFor(Class<?> iface) throws SQLException { return original.isWrapperFor(iface); }
}
