// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/monitoring","id":"1"},"2":{"name":"系统监控","path":"/monitoring","icon":"MonitorOutlined","id":"2"},"3":{"path":"/monitoring","redirect":"/monitoring/overview","parentId":"2","id":"3"},"4":{"name":"系统概览","path":"/monitoring/overview","parentId":"2","id":"4"},"5":{"name":"JVM信息","path":"/monitoring/jvm","parentId":"2","id":"5"},"6":{"name":"内存使用","path":"/monitoring/memory","parentId":"2","id":"6"},"7":{"name":"线程信息","path":"/monitoring/threads","parentId":"2","id":"7"},"8":{"name":"GC信息","path":"/monitoring/gc","parentId":"2","id":"8"},"9":{"name":"数据库连接池","path":"/monitoring/dbpool","parentId":"2","id":"9"},"10":{"name":"HTTP指标","path":"/monitoring/http","parentId":"2","id":"10"},"11":{"name":"业务指标","path":"/monitoring/business","parentId":"2","id":"11"},"12":{"name":"自定义指标","path":"/monitoring/custom","parentId":"2","id":"12"},"13":{"name":"缓存管理","path":"/cache","icon":"DatabaseOutlined","id":"13"},"14":{"name":"SQL统计","path":"/sql","icon":"BarChartOutlined","id":"14"},"15":{"name":"系统测试","path":"/testing","icon":"BugOutlined","id":"15"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Monitoring__index" */'@/pages/Monitoring/index.jsx')),
'3': React.lazy(() => import('./EmptyRoute')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Monitoring__index" */'@/pages/Monitoring/index.jsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Monitoring__index" */'@/pages/Monitoring/index.jsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Monitoring__index" */'@/pages/Monitoring/index.jsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Monitoring__index" */'@/pages/Monitoring/index.jsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Monitoring__index" */'@/pages/Monitoring/index.jsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Monitoring__index" */'@/pages/Monitoring/index.jsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__Monitoring__index" */'@/pages/Monitoring/index.jsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__Monitoring__index" */'@/pages/Monitoring/index.jsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__Monitoring__index" */'@/pages/Monitoring/index.jsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__CacheManagement__index" */'@/pages/CacheManagement/index.jsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__SqlStatistics__index" */'@/pages/SqlStatistics/index.jsx')),
'15': React.lazy(() => import(/* webpackChunkName: "p__Testing__index" */'@/pages/Testing/index.jsx')),
},
  };
}
