apiVersion: v1
kind: Namespace
metadata:
  name: a8-turbo
  labels:
    name: a8-turbo
    app.kubernetes.io/name: a8-turbo
    app.kubernetes.io/version: "0.0.8-alpha"
---
apiVersion: v1
kind: Namespace
metadata:
  name: a8-turbo-monitoring
  labels:
    name: a8-turbo-monitoring
    app.kubernetes.io/name: a8-turbo-monitoring
    app.kubernetes.io/component: monitoring