ServerName phpredmin
Alias /phpredmin /var/www/html/phpredmin/public

<Directory /var/www/html/phpredmin/public>
    AllowOverride All
    Require all granted
</Directory>

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /phpredmin
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /phpredmin/index.php [L]
</IfModule>