database: shopdb
including-tables: "shopdb.*"

mysql.conf.hostname: mysql
mysql.conf.username: root
mysql.conf.password: "a8"  # 密码若有特殊字符需加引号
mysql.conf.port: 3306
mysql.conf.database-name: shopdb

sink.conf.load-url: starrocks:8030
sink.conf.username: root
sink.conf.password: ""
sink.conf.jdbc-url: jdbc:mysql://starrocks:9030
sink.conf.sink.label-prefix: shopdb

table.conf.replication_num: 1
table.conf.fast_schema_evolution: true