################################################################################
# Description: Sync MySQL all tables to StarRocks
################################################################################
source:
  type: mysql
  hostname: mysql
  port: 3306
  username: root
  password: a8
  tables: shopdb.\.*
  server-id: 5900-5904
  server-time-zone: UTC

sink:
  type: starrocks
  name: StarRocks Sink
  jdbc-url: jdbc:mysql://starrocks:9030
  load-url: starrocks:8080
  username: root
  password: ""
  table.create.properties.replication_num: 1

pipeline:
  name: Sync MySQL Database to StarRocks
  parallelism: 2
