-- Grant LogMiner CDC privileges to cdc_user
ALTER SESSION SET CONTAINER = XEPDB1;
GRANT CREATE SESSION, EXECUTE_CATALOG_ROLE, SELECT ANY TRANSACTION, 
      SELECT ANY DICTIONARY, LOGMINING TO cdc_user;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
