-- 1. Enable Supplemental Logging at CDB level
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- 2. Memory Optimization for Low-Resource Environments (Set before switch)
-- Shrink SGA and PGA to fit in 2GB container
ALTER SYSTEM SET SGA_TARGET = 1G SCOPE=BOTH;
ALTER SYSTEM SET PGA_AGGREGATE_TARGET = 256M SCOPE=BOTH;

-- 3. Switch to PDB and configure cdc_user
ALTER SESSION SET CONTAINER = FREEPDB1;

-- 4. Grant privileges for LogMiner / CDC
GRANT CREATE SESSION TO cdc_user;
GRANT SELECT ANY TRANSACTION TO cdc_user;
GRANT SELECT ANY DICTIONARY TO cdc_user;
GRANT EXECUTE_CATALOG_ROLE TO cdc_user;
GRANT LOGMINING TO cdc_user;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO cdc_user;
GRANT SELECT ON V_$LOGMNR_LOGS TO cdc_user;
GRANT SELECT ON V_$LOGMNR_PRIVS TO cdc_user;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO cdc_user;
GRANT SELECT ON V_$LOGMNR_SESSION TO cdc_user;
GRANT SELECT ON V_$LOGMNR_STATS TO cdc_user;

-- 5. Enable Supplemental Logging at PDB level
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- 6. Create Business Application User
-- Oracle 19c EE PDB user
CREATE USER a8user IDENTIFIED BY a8password;
GRANT CONNECT, RESOURCE TO a8user;
ALTER USER a8user QUOTA UNLIMITED ON USERS;
