# Kong configuration file
# See https://docs.konghq.com/gateway/latest/reference/configuration/

# Database settings
database = off

# Declarative config file
declarative_config = /opt/kong/kong.yml

# Proxy settings
proxy_listen = 0.0.0.0:8000, 0.0.0.0:8443 ssl

# Admin API settings
admin_listen = 0.0.0.0:8001, 0.0.0.0:8444 ssl

# Log level
log_level = notice

# Prefix
prefix = /usr/local/kong

# Allow access to Admin API from other containers in the same network
trusted_ips = 0.0.0.0/0